/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */

  docsSidebar: [
    'introduction',
    {
      type: 'category',
      label: 'Getting Started',
      description: 'Getting started with NodeArch',
      collapsed: false,
      items: [
        'installation',
        'hello-world',
        'configuration'
      ]
    },
    {
      type: 'category',
      label: 'Concept',
      description: 'NodeArch core concepts',
      collapsed: true,
      items: [
        'hook',
        'controller',
        'service'
      ]
    },
    {
      type: 'category',
      label: 'Guides',
      description: 'Guides for common use cases',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides'
        }
      ]
    },
    {
      type: 'category',
      label: 'Extensions',
      description: 'All about NodeArch Extensions development and available extensions',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Official Extensions',
          link: {
            type: 'generated-index'
          },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'extensions/official'
            }
          ]
        },
        {
          type: 'category',
          label: 'Community Extensions',
          link: {
            type: 'generated-index'
          },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'extensions/community'
            }
          ]
        },
        {
          type: 'category',
          label: 'Extension Development',
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'extensions/development'
            }
          ]
        },
      ]
    },

    // {
    //   type: 'category',
    //   label: 'Extensions',
    //   collapsed: true,
    //   items: [
    //     'extensions/express',
    //     'extensions/socket-io',
    //     'extensions/keycloak',
    //     'extensions/vault',
    //   ]
    // },
    // {
    //   type: 'category',
    //   label: 'Extension Development',
    //   collapsed: true,
    //   items: [
    //     'extension-api/create-extension'
    //   ]
    // },
    {
      type: 'category',
      label: 'Architecture',
      description: 'NodeArch architecture overview',
      collapsed: true,
      items: [
        'architecture-overview',
        'app-lifecycle',
        'dependency-injection'
      ]
    },
    // {
    //   type: 'category',
    //   label: 'Contributing',
    //   items: [
    //     'create-extension'
    //   ]
    // }
  ]

};

module.exports = sidebars;
